name: Blog
on:
  push:
    branches:
      - pages
      # - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: markout
      - uses: actions/deploy-pages@v4
